apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rolebinding-for-serviceaccount
  namespace: default
subjects:
- kind: ServiceAccount
  name: admin-serviceaccount
  namespace: default
roleRef:
  kind: Role
  name: role-for-serviceaccount
  apiGroup: rbac.authorization.k8s.io